[project]
name = ""
version = ""
description = ""
authors = [
    {name = "VVVVictorJ", email = "956951190@qq.com"},
]
dependencies = [
    "requests>=2.31.0",
    "aiomysql>=0.2.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

