import cx_Oracle

connection = cx_Oracle.connect(user="xhadmin", password="bjtest",
                               dsn="10.70.86.2:1521/dbtestbj")
cursor = connection.cursor()

# sql = """INSERT INTO BJAPP.T_CPCT_ASSIGNATION_COUNT
# (ASSIGNATION_COUNT_ID, CONTRACT_NO, IS_RECKON_IN_LABORRATE, ASSIGNATION_COUNT, ICS_CODE, ASSIGNATION_TYPE, CREATE_DATE)
# VALUES(19999, 'ABC1806', '22', 14, NULL, NULL, TIMESTAMP '2022-05-09 15:59:18.000000')
# """

sql = """INSERT INTO XHCP.T_CPCT_BILL
(BILL_ID, SETTLE_D_ID, DATA_FLAG, OP_FLAG, BILL_TYPE_CODE, EXPANSE_REPORT_ID, SYS_ID, PROGRAM_CODE, RESP_UNIT_ID, REPORT_DATE, REPORT_UNIT_ID, ACCOUNT_ID, REPORTOR_CODE, SUPPLIER_CODE, SUPPLIER_TYPE, SUPPLIER_NAME, SUPPLIER_ACCOUNT, SUPPLIER_ACCOUNT_ID, SUPPLIER_TAX_NO, SUPPLIER_BANK_NAME, SUPPLIER_BANK_TYPE, SUPPLIER_BANK_CODE, SUPPLIER_ADDRESS, SUPPLIER_ZIP_CODE, SUPPLIER_PHONE, SUPPLIER_EMAIL, TOTAL_AMOUNT, COUNTERACT_DATE, COUNTERACT_AMOUNT, REMAIN_AMOUNT, CURRENCY_CODE, BILLS_N, SUBROGATION_MARK, SUBROGATION_CODE, RECEIPT_NO, CONFIRM_ID, BILL_STATUS, ALIVE_FLAG, REC_CREATOR, REC_CREATE_TIME, REC_REVISOR, REC_REVISE_TIME, SEND_STATUS, BILL_DESC, COMMIT_TIME)
VALUES(4, 62, NULL, NULL, 'P04001', 'BK516000161', NULL, NULL, NULL, TIMESTAMP '2016-09-13 00:00:00.000000', NULL, NULL, '154866', '057280', NULL, '江苏国泰南园宾馆有限公司', '56789876564454678', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 123, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'RK5160000201', NULL, '10', '1', '154866', TIMESTAMP '2016-09-23 18:04:07.000000', NULL, NULL, NULL, '都是发的', NULL)
"""

try:
    data_insert = cursor.execute(sql)
    print(data_insert)
except Exception as e:
    print(e)
connection.commit()
connection.close()
